name: Generate Documentation

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/generate-docs.yml'
            - 'source/**.js'

jobs:
    generate:
        name: JSDoc
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: source
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

            - name: Install Dependencies
              run: npm install
        
            - name: Compile Docs
              run: npm run doc

            - name: Commit and Push
              uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: 'Update JSDoc from Github Actions (Documentation Generation)'