name: Unit Tests

on: 
  push:
     paths:
       - 'source/__tests__/**.js'
       - 'source/public/**.js'
jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: source
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test
